config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :categories do
    resources :payments
  end

  resources :users

  root 'users#splash'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, User

    return unless user.present?

    can :manage, Category, user: user
    can :manage, Payment, user:
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :category_payment, dependent: :destroy
  has_many :payments, through: :category_payment

  validates :name, presence: true
  validates :icon, presence: true

  def total_amount
    payments.sum(:amount)
  end
end

app/models/category_payment.rb
class CategoryPayment < ApplicationRecord
  belongs_to :category
  belongs_to :payment
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :category_payment, dependent: :destroy
  has_many :categories, through: :category_payment

  validates :name, presence: true
  # allow float
  validates :amount, presence: true, numericality: { greater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :categories, dependent: :destroy
  has_many :payments, dependent: :destroy

  validates :name, :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :update_allowed_parameters, if: :devise_controller?

  def after_sign_in_path_for(_resource)
    categories_path
  end

  def after_sign_up_path_for(_resource)
    categories_path
  end

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :current_password)
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only: %i[show edit update destroy]

  def index
    @categories = Category.where(author_id: current_user.id)
  end

  def show; end

  def new
    @category = Category.new
  end

  def edit; end

  def create
    @category = Category.new(category_params)
    @category.author_id = current_user.id

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_path, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @payments = @category.payments
    @payments.each(&:destroy)
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_category, only: %i[new create edit update destroy]
  before_action :set_payment, only: %i[edit update destroy]

  # GET /payments/new
  def new
    @payment = Payment.new
  end

  # GET /payments/1/edit
  def edit; end

  # POST /payments or /payments.json
  def create
    @payment = @category.payments.new(payment_params)
    @payment.author_id = current_user.id

    respond_to do |format|
      if @payment.save
        format.html { redirect_to @category, notice: 'payment was successfully created.' }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1 or /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to @category, notice: 'payment was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1 or /payments/1.json
  def destroy
    @payment.destroy

    respond_to do |format|
      format.html { redirect_to @category, notice: 'payment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_payment
    @payment = payment.find(params[:id])
  end

  def set_category
    @category = Category.find(params[:category_id])
  end

  # Only allow a list of trusted parameters through.
  def payment_params
    params.require(:payment).permit(:name, :amount).merge(author_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def splash
    @current_user = current_user
    authorize! :read, User
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end
end

app/views/categories/_category.html.erb
<div class="category_card">
  <div class="category_card_left">
    <p class="category_icon">
      <%= image_tag "#{category.icon}", style: 'height:50px; width:50px;' %>
    </p>
    <p><%= category.name %></p>
  </div>
  <p>$ <%= category.total_amount %></p>
</div>

app/views/categories/_form.html.erb
<%= render 'partials/page_header' %>
<%= form_with(model: @category) do |form| %>
  <section class="form-section">
    <%= form.text_field :name,
    class: "text_input",
    placeholder: "Name of Category...", class: "form-field" %>
  </section>

  <section class="form-section">
    <%= form.text_field :icon,
    class: "text_input",
    placeholder: "Link of icon...", class: "form-field" %>
  </section>

  <section class="actions pt-30">
    <%= form.submit "Add Category", class: "btn login-btn" %>
  </section>
<% end %>

app/views/categories/edit.html.erb
<%= render "form", category: @category %>

app/views/categories/index.html.erb
<p style="color: green"><%= notice %></p>
  <br>
  <%= render 'partials/page_header' %>
  <% @categories.each do |category| %>
    <%= link_to category do %>
      <div class="page-items-list">
        <div class="category-details">
          <%= image_tag "#{category.icon}", style: 'height:50px; width:50px;' %>
          <div><%= category.name %></div>
        </div>
        <div>$<%= category.total_amount %></div>
      </div>
    <% end %>
  <% end %>
  <div><%= link_to "Add a Category", new_category_path, class: "btn login-btn bottom-button" %></div>
</div>

app/views/categories/new.html.erb
<%= render "form", category: @category %>

app/views/categories/show.html.erb
<div class="page-body">
  <div style="background: white">
  <%= render 'partials/page_header' %><br><br>
    <div class="payment-header">
      <div class="category-header-details">
        <div><%= image_tag "#{@category.icon}", class: "show-page-icon" %></div>
        <div><%= @category.name %></div>
      </div>
      <div>
        <%= @category.total_amount %>
      </div>
    </div>
    <br>
  </div>
  <div class="blank-div"></div>
  <%= render @category.payments.order(created_at: :desc) %>
  <%= link_to "Add a Payment", new_category_payment_path(@category), class: "btn login-btn bottom-button" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://code.iconify.design/2/2.2.1/iconify.min.js"></script>
  </head>
  <body>
    <% unless current_page?(root_path) %>
      <%= render partial: 'partials/navigation'%>
    <% end %>
  
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/partials/_navbar_icon.html.erb
<%if current_user%>
  <% if current_page?(categories_path) %>
    <%= image_tag("hamburger.svg", :alt => "hamburger", :class => "svg-icon-ham") %>
  <% else %>
    <% if @category %>
      <% if @category.id == nil && current_page?(new_category_path) %>
        <%= link_to categories_path, class:"link_li" do %>
          <%= image_tag("arrow-back.svg", :alt => "arrow-back", :class => "svg-icon-ham") %>
        <% end %>
      <% end %>
      <% if @category.id != nil && current_page?(category_path(@category)) %>
        <%= link_to categories_path, class:"link_li" do %>
          <%= image_tag("arrow-back.svg", :alt => "arrow-back", :class => "svg-icon-ham") %>
        <% end %>
      <% end %>
      <% if @category.id != nil && current_page?(edit_category_path(@category)) %>
        <%= link_to category_path(@category), class:"link_li" do %>
          <%= image_tag("arrow-back.svg", :alt => "arrow-back", :class => "svg-icon-ham") %>
        <% end %>
      <% end %>
    <% end %>
    <% if @payment && @category %>
      <% if @payment.id == nil && current_page?(new_category_payment_path(@category)) %>
        <%= link_to category_path(@category), class:"link_li" do %>
          <%= image_tag("arrow-back.svg", :alt => "arrow-back", :class => "svg-icon-ham") %>
        <% end %>
      <% end %>
      <% if @payment.id != nil && current_page?(edit_category_payment_path(@category, @payment)) %>
        <%= link_to category_path(@category), class:"link_li" do %>
          <%= image_tag("arrow-back.svg", :alt => "arrow-back", :class => "svg-icon-ham") %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
<% else %>
  <%= link_to root_path, class:"link_li" do %>
    <%= image_tag("hamburger.svg", :alt => "hamburger", :class => "svg-icon-ham") %>
  <% end %>
<%end%>

app/views/partials/_navbar_title.html.erb
<% if current_page?(new_user_session_path) %>
  LOG IN
<% end %>
<% if current_page?(new_user_registration_path) %>
  REGISTER
<% end %>
<% if current_page?(new_user_password_path) %>
  FORGOT PASSWORD
<% end %>
<% if @category %>
  <% if @category.id == nil && current_page?(new_category_path) %>
    NEW CATEGORY
  <% end %>
  <% if @category.id != nil && current_page?(category_path(@category)) %>
    CATEGORY
  <% end %>
  <% if @category.id != nil && current_page?(edit_category_path(@category)) %>
    EDIT CATEGORY
  <% end %>
<% end %>
<% if @payment && @category %>
  <% if @payment.id == nil && current_page?(new_category_payment_path(@category)) %>
    NEW TRANSACTION
  <% end %>
  <% if @payment.id != nil && current_page?(edit_category_payment_path(@category, @payment)) %>
    EDIT TRANSACTION
  <% end %>
<% end %>
<% if current_page?(categories_path) %>
  CATEGORIES
<% end %>

app/views/partials/_navigation.html.erb
<header>
  <nav>
    <ul class="navbar-list">
      <li>
        <%= render partial: 'partials/navbar_icon' %>
      </li>
      <li>
        <p><%= render partial: 'partials/navbar_title' %></p>
      </li>
      <li>
        <% if current_user %>
          <%= link_to destroy_user_session_path, method: :delete do %>
            <%= image_tag("logout.svg", :alt => "arrow-back", :class => "svg-icon-ham") %>
          <% end %>
        <% else %>
          <%= link_to new_user_session_path do %>
            <span data-icon="charm:sign-in"></span>
          <% end %>
        <%end%>
      </li>
    </ul>
  </nav>
</header>

app/views/partials/_page_header.html.erb
<br><br><br>

app/views/payments/_form.html.erb
<br>
<br>
<br>
<div>
  <%= form_with(model: [@category, @payment]) do |form| %>
    <div class="field">
      <%= form.text_field :name, value: @payment.name, placeholder: "Name", required: true, class: "form-field" %>
    </div>
    <div class="field">
      <%= form.text_field :amount, value: @payment.amount, placeholder: "Amount", type: "float", required: true, class: "form-field" %>
    </div>
    <div class="actions pt-30">
      <%= form.submit "Add Payment", class: "btn login-btn" %>
    </div>
  <% end %>
</div>

app/views/payments/_payment.html.erb
 <div class="card-link">
  <div class="category-card">
    <p><%= payment.name %></p>
    <p>$ <%= payment.amount %></p>
  </div>
</div>

app/views/payments/edit.html.erb
<%= render "form", payment: @payment %>

app/views/payments/new.html.erb
<%= render "form", payment: @payment %>

app/views/users/splash.html.erb
<div class="splash-screen">
  <h1 class="splash-text">کھاتہ</h1>
  <div class="reg-buttons-div">
    <%= link_to "Log In", new_user_session_path, class: "login-btn" %>
    <%= link_to "Sign Up", new_user_registration_path, class: "reg-btn" %>
  </div>
</div>